### ISSUE TITLE
Figures linked to old gpgLabs repos with absolute URL

### ISSUE THREAD

**Issue by yangdikun** [geoscixyz/geosci-labs#11]
![image](https://user-images.githubusercontent.com/5066933/51803380-74fe4780-228f-11e9-8e12-7d1cc7fb02f0.png)

We also need to fix this referencing because eventually gpgLabs will be taken offline.

BTW: is it possible to have relative URL, so we don't care what the package is called.

**Comment by yangdikun** [comment]
Actually I just found another solution. Not sure if this option has been discussed. (https://stackoverflow.com/questions/51975699/embedding-image-into-jupyter-notebook-and-exporting-to-html)

First, encode your image as Base64, e.g. by using one of the online enocders.
Create a markdown cell and include an <img> tag which uses your Base64 code, e.g.:

<img src="data:image/png;base64,CODE_FOLLOWS_HERE" />

We can embed the images as base64 code in the notebook, so the images are saved with notebooks. The good thing is the display of images does not depend on external links.

I just quickly tried it and it worked well.

**Comment by lheagy** [comment]
Thanks @yangdikun, that is interesting. The thing that I am concerned with is that it likely will become harder to version the images and is less transparent to others who might want to improve an image how they can contribute (if using a url, it is clear where it needs to be updated, but encoding an image is subtle). This repo name should not change, so this should be a one-time fix
