### ISSUE TITLE
getting testing back up and running 

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/geosci-labs#30]
We can no longer rely on TravisCI for testing, so we should look at getting testing up and running elsewhere. What do folks think of using github actions for this (cc @jcapriot)?

**Comment by thast** [comment]
Is that different than the azure pipelines we use for SimPEG?

**Comment by lheagy** [comment]
It is different than azure pipelines that we use for SimPEG. My impression is that it is a bit more lightweight than azure pipelines. Since the testing / testing matrix we set up here is pretty simple, I think it might be a good solution. SimPEG has a bit more of a complex testing setup, so azure seems fitting there.
