### ISSUE TITLE
Mag apps: 'SimPEG.PF.Magnetics' has no attribute 'get_T_mat'

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/geosci-labs#8]
![image](https://user-images.githubusercontent.com/6361812/51577299-3e2ec880-1e6e-11e9-815b-295779fe775c.png)

@fourndo, @thast : I think this is related to the latest potential fields updates? Would you mind taking a look at the mag apps when you have a chance? I was running: MagneticPrismApplet.ipynb, but I am guessing this impacts a few of them

**Comment by fourndo** [comment]
Worked on #10 .

**Comment by thast** [comment]
solved? @fourndo  @lheagy

**Comment by fourndo** [comment]
yip
